### ISSUE TITLE
[Help] I need help setting up Codecov

### ISSUE THREAD

**Issue by GuillouTran** [chrisvogt/gatsby-theme-private-sphere#55]
I can't figure out how to setup codecov properly

**Comment by chrisvogt** [comment]
Hi @GuillouTran, is this for GuillouTran/guilloutran.com? If so, I think what I'm doing will work for you. I'm trying to remember how I have this setup. 🤔

* I'm [using Jest](https://github.com/chrisvogt/gatsby-theme-private-sphere/blob/master/theme/package.json#L28) – `jest --coverage` in _package.json_ – to run tests and generate the code coverage report, which gets uploaded to Codecov.
* I tried to use the [Codecov GitHub app](https://github.com/apps/codecov), but remember struggling to get it working.
* In the end, I used [the bash upload script](https://docs.codecov.io/docs/about-the-codecov-bash-uploader) and created a Codecov task to upload the coverage report, which you can see here (https://github.com/chrisvogt/gatsby-theme-private-sphere/blob/master/.circleci/config.yml#L37). In the environmental variable for that CircleCI project, I have a `CODECOV_TOKEN` set.

To do the same for your repo:

1. Verify that your coverage report is being generated and saved (look for a `/coverage` directory with `lcov` files in it).
2. Update [your CircleCI config](https://github.com/GuillouTran/guilloutran.com/blob/master/.circleci/config.yml) and copy in [my Codecov task](https://github.com/chrisvogt/gatsby-theme-private-sphere/blob/master/.circleci/config.yml#L37).
3. You _may_ (?) need to set a `CODECOV_TOKEN` environmental variable in CircleCI, but I can't remember if that was truly necessary.

One more thing: the tests I have for this repository are not good and I want to update and rewrite them. I don't recommend following what I'm doing inside my `*.spec.js` files. They were an experiment with [Jest snapshot tests](https://jestjs.io/docs/en/snapshot-testing), and are making my code coverage report look inflated. I don't feel the tests currently in this project are useful, and I plan to erase and replace them with good tests – probably integration tests, but still written in Jest.

**Comment by chrisvogt** [comment]
Closing this for now. Let me know if you have any questions!
